#!/usr/bin/env python3
"""Record a human-testing UAT result and feed it back into the planning docs.

Owns the UAT acceptance ledger (`.planning/UAT-RESULTS.md`) and keeps a one-line
acceptance marker in `.planning/STATE.md` under `## Deferred Verification` in sync.
The canonical UAT registry mirrors `docs/HUMAN-TESTING-PLAN.md`. Deterministic and
side-effect-scoped: pass `--results-file`/`--state-file` to target temp copies (tests do).

Examples:
    python3 scripts/testing/record_uat.py --list
    python3 scripts/testing/record_uat.py --id UAT-05 --result pass --notes "eval_truth 1.0"
    python3 scripts/testing/record_uat.py --id E2E-03 --result fail --notes "cover letter Gate B miss"
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path

# Canonical UAT registry — order = display order. Mirrors docs/HUMAN-TESTING-PLAN.md Part 4.
UAT_REGISTRY: list[tuple[str, str]] = [
    ("UAT-02", "Live SubagentStop hook blocks malformed envelope"),
    ("UAT-03a", "offer-scout board-search ranking + scope"),
    ("UAT-03b", "offer-scout single-offer fielding + hash stability"),
    ("UAT-3.1a", "jpeg credential vision extraction"),
    ("UAT-3.1b", "full live ingestion analyzer -> configurator"),
    ("UAT-04a", "three isolated per-type drafts"),
    ("UAT-04b", "targeted structured-feedback retry"),
    ("UAT-05", "Gate A truth accuracy on adversarial set"),
    ("UAT-06", "Gate B coverage_map + Gate C polish"),
    ("UAT-07", "Live runtime: mode parity / cap / fan-out / resume"),
    ("E2E-03", "Live real-offer run -> 3 gate-passing artifacts"),
]
# The two items that gate behavioral acceptance of the milestone.
GATING_IDS = ("UAT-05", "E2E-03")

RESULTS = ("pass", "fail", "blocked", "pending")
GLYPH = {"pass": "PASS", "fail": "FAIL", "blocked": "BLOCKED", "pending": "pending"}
MARK = {"pass": "[x]", "fail": "[!]", "blocked": "[b]", "pending": "[ ]"}

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RESULTS = REPO_ROOT / ".planning" / "UAT-RESULTS.md"
DEFAULT_STATE = REPO_ROOT / ".planning" / "STATE.md"

_ROW_RE = re.compile(r"^\|\s*(?P<id>[A-Za-z0-9.\-]+)\s*\|.*\|\s*(?P<result>\w+)\s*\|\s*(?P<date>[^|]*?)\s*\|\s*(?P<notes>[^|]*?)\s*\|\s*$")


def _default_records() -> dict[str, dict]:
    return {uid: {"result": "pending", "date": "-", "notes": "-"} for uid, _ in UAT_REGISTRY}


def load_records(results_path: Path) -> dict[str, dict]:
    """Load recorded results from the ledger; seed defaults for any unknown/missing id."""
    records = _default_records()
    if not results_path.is_file():
        return records
    for line in results_path.read_text(encoding="utf-8").splitlines():
        m = _ROW_RE.match(line)
        if not m:
            continue
        uid = m.group("id")
        if uid not in records:  # ignore header rows ("ID") and anything off-registry
            continue
        res = m.group("result").strip().lower()
        if res not in RESULTS:
            continue
        records[uid] = {
            "result": res,
            "date": (m.group("date").strip() or "-"),
            "notes": (m.group("notes").strip() or "-"),
        }
    return records


def acceptance_summary(records: dict[str, dict]) -> str:
    recorded = sum(1 for r in records.values() if r["result"] != "pending")
    total = len(UAT_REGISTRY)
    gates = " · ".join(f"{gid} {GLYPH[records[gid]['result']]}" for gid in GATING_IDS)
    accepted = all(records[gid]["result"] == "pass" for gid in GATING_IDS)
    verdict = "ACCEPTED" if accepted else "not yet accepted"
    return f"{recorded}/{total} recorded · gating: {gates} · behavioral acceptance: {verdict}"


def render_ledger(records: dict[str, dict], updated: str) -> str:
    lines = [
        "# UAT Acceptance Ledger — give-me-job v1.0",
        "",
        "> Regenerated by `scripts/testing/record_uat.py`. Test steps: `docs/HUMAN-TESTING-PLAN.md`.",
        f"> Last updated: {updated}",
        "",
        "| ID | Test | Result | Date | Notes |",
        "|----|------|--------|------|-------|",
    ]
    desc = dict(UAT_REGISTRY)
    for uid, _ in UAT_REGISTRY:
        r = records[uid]
        lines.append(f"| {uid} | {desc[uid]} | {GLYPH[r['result']]} | {r['date']} | {r['notes']} |")
    lines += ["", f"**Acceptance:** {acceptance_summary(records)}", ""]
    return "\n".join(lines)


def update_state_marker(state_path: Path, records: dict[str, dict], updated: str) -> bool:
    """Insert/replace the one-line acceptance marker under '## Deferred Verification'. Returns True if changed."""
    if not state_path.is_file():
        return False
    text = state_path.read_text(encoding="utf-8")
    marker = f"> **UAT acceptance:** {acceptance_summary(records)} — see `.planning/UAT-RESULTS.md` (updated {updated})."
    heading = "## Deferred Verification"
    if heading not in text:
        return False
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    inserted = False
    while i < len(lines):
        if lines[i].strip() == heading and not inserted:
            out.append(lines[i])
            i += 1
            # Consume any existing blank lines + a prior marker directly under the heading,
            # then emit exactly one blank + one marker + one blank. Idempotent by construction.
            while i < len(lines) and (lines[i].strip() == "" or lines[i].startswith("> **UAT acceptance:**")):
                i += 1
            out.extend(["", marker, ""])
            inserted = True
            continue
        out.append(lines[i])
        i += 1
    new_text = "\n".join(out)
    if not text.endswith("\n"):
        pass
    elif not new_text.endswith("\n"):
        new_text += "\n"
    if new_text != text:
        state_path.write_text(new_text, encoding="utf-8")
        return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Record a UAT result and sync planning docs.")
    parser.add_argument("--id", help="UAT id (e.g. UAT-05, E2E-03)")
    parser.add_argument("--result", choices=RESULTS, help="pass | fail | blocked | pending")
    parser.add_argument("--notes", default="", help="short evidence / one-line note")
    parser.add_argument("--list", action="store_true", help="print current status and exit")
    parser.add_argument("--results-file", type=Path, default=DEFAULT_RESULTS)
    parser.add_argument("--state-file", type=Path, default=DEFAULT_STATE)
    parser.add_argument("--date", help="override date (YYYY-MM-DD) — default today")
    args = parser.parse_args()

    updated = args.date or datetime.date.today().isoformat()
    records = load_records(args.results_file)

    if args.list and not args.id:
        for uid, desc in UAT_REGISTRY:
            r = records[uid]
            gate = " (gating)" if uid in GATING_IDS else ""
            print(f"{MARK[r['result']]} {uid:<8} {GLYPH[r['result']]:<8} {desc}{gate}"
                  + (f"  — {r['notes']}" if r["notes"] != "-" else ""))
        print(f"\nAcceptance: {acceptance_summary(records)}")
        return 0

    valid_ids = {uid for uid, _ in UAT_REGISTRY}
    if not args.id or args.id not in valid_ids:
        print(f"error: --id must be one of: {', '.join(sorted(valid_ids))}", file=sys.stderr)
        return 1
    if not args.result:
        print("error: --result is required when recording (pass|fail|blocked|pending)", file=sys.stderr)
        return 1

    records[args.id] = {
        "result": args.result,
        "date": updated,
        "notes": (args.notes.strip().replace("|", "/") or "-"),
    }

    try:
        args.results_file.parent.mkdir(parents=True, exist_ok=True)
        args.results_file.write_text(render_ledger(records, updated), encoding="utf-8")
    except OSError as exc:
        print(f"error: could not write ledger: {exc}", file=sys.stderr)
        return 1

    state_changed = update_state_marker(args.state_file, records, updated)

    print(f"recorded {args.id} = {GLYPH[args.result]}")
    print(f"ledger:  {args.results_file}")
    print(f"state:   {'marker updated' if state_changed else 'marker unchanged'}")
    print(f"summary: {acceptance_summary(records)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
